# Generated by Django 6.1.1 on 2026-09-25 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='PLANNED', max_length=10)),
                ('final_meal_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('final_total_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rounding_residual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='months_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_roles', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='months.month')),
            ],
        ),
        migrations.CreateModel(
            name='MonthMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateField()),
                ('left_on', models.DateField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lunch_count', models.PositiveIntegerField(default=0)),
                ('dinner_count', models.PositiveIntegerField(default=0)),
                ('meal_units', models.PositiveIntegerField(default=0)),
                ('guest_lunch_count', models.PositiveIntegerField(default=0)),
                ('guest_dinner_count', models.PositiveIntegerField(default=0)),
                ('guest_meal_units', models.PositiveIntegerField(default=0)),
                ('meal_rate_applied', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('meal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guest_meal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_deposit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_memberships', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='months.month')),
            ],
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('status',), name='unique_open_month'),
        ),
        migrations.AddConstraint(
            model_name='managerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at', None)), fields=('month',), name='unique_active_manager_per_month'),
        ),
        migrations.AlterUniqueTogether(
            name='monthmember',
            unique_together={('month', 'member')},
        ),
    ]
