# Generated by Django 5.2.17 on 2026-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='PLANNED', max_length=20)),
                ('final_meal_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('final_total_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_total_meal_units', models.PositiveIntegerField(blank=True, null=True)),
                ('rounding_residual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_count', models.IntegerField(default=0)),
                ('last_reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateField()),
                ('left_on', models.DateField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lunch_count', models.PositiveIntegerField(default=0)),
                ('dinner_count', models.PositiveIntegerField(default=0)),
                ('meal_units', models.PositiveIntegerField(default=0)),
                ('guest_lunch_count', models.PositiveIntegerField(default=0)),
                ('guest_dinner_count', models.PositiveIntegerField(default=0)),
                ('guest_meal_units', models.PositiveIntegerField(default=0)),
                ('meal_rate_applied', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('meal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guest_meal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_deposit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
