# Generated by Django 5.2.17 on 2026-09-19 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('months', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managerassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_manager_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerassignment',
            name='unassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unassigned_manager_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_months', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='month',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_months', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='month',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_months', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerassignment',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='months.month'),
        ),
        migrations.AddField(
            model_name='monthmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthmember',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='months.month'),
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='check_month_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('status',), name='unique_open_month'),
        ),
        migrations.AddConstraint(
            model_name='managerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('month',), name='unique_active_manager_per_month'),
        ),
        migrations.AddConstraint(
            model_name='monthmember',
            constraint=models.UniqueConstraint(fields=('month', 'member'), name='unique_month_member'),
        ),
    ]
