# Generated by Django 5.2.17 on 2026-09-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_name', models.CharField(max_length=255)),
                ('mess_address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('meal_submission_deadline', models.TimeField()),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=100)),
                ('currency', models.CharField(default='BDT', max_length=20)),
                ('guest_meal_enabled', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='single_system_setting')],
            },
        ),
    ]
