# Generated by Django 6.1.1 on 2026-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('mess_name', models.CharField(default='My Mess', max_length=128)),
                ('meal_submission_deadline', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64)),
                ('currency', models.CharField(default='BDT', max_length=8)),
            ],
        ),
    ]
