# Generated by Django 5.2.17 on 2026-09-19 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        ('months', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='last_corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='months.month'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('member', 'meal_date'), name='unique_member_meal_date'),
        ),
    ]
