# Generated by Django 5.2.17 on 2026-09-19 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest_meals', '0001_initial'),
        ('months', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmeal',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestmeal',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_meals', to='months.month'),
        ),
        migrations.AddField(
            model_name='guestmeal',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_guest_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='guestmeal',
            constraint=models.CheckConstraint(condition=models.Q(('lunch_quantity__gt', 0), ('dinner_quantity__gt', 0), _connector='OR'), name='check_guest_meal_has_quantity'),
        ),
        migrations.AddConstraint(
            model_name='guestmeal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'REJECTED'), _negated=True), fields=('member', 'meal_date'), name='unique_active_guest_meal_per_date'),
        ),
    ]
